
GET http://localhost:6080/posts
Authorization: Bearer .eyJpYXQiOjE2Nzk4NDQzOTJ9.FQCPYOqnhSQpPDYWeyDbDDcL2bYdpyJ7TRTghGMJbK4


###


POST http://localhost:6080/login
 
Content-Type: application/json


{
    "username":"vik"
}